App_Blog/urls.py
from django.urls import path
from . import views

app_name = "App_Blog"

urlpatterns = [
    path("", views.BlogList.as_view(), name="blog_list"),
    path("write/", views.CreateBlog.as_view(), name="create_blog"),
    path("details/<slug:slug>/", views.blog_details, name="blog_details"),
    path("liked/<pk>/", views.liked, name="liked_post"),
    path("unliked/<pk>/", views.unliked, name="unliked_post"),
    path("disliked/<pk>/", views.disliked, name="disliked_post"),
    path("undisliked/<pk>/", views.undisliked, name="undisliked_post"),
    path("myblogs/", views.MyBlog.as_view(), name="my_blogs"),
    path("edit/<pk>/", views.UpdateBlog.as_view(), name="edit_blog"),
]

App_Login/urls.py
from django.urls import path
from App_Login import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('password/', views.change_password, name='change_password'),
    path('add_profile_pic/', views.add_profile_pic, name='add_profile_pic'),
    path('change_profile_pic/', views.change_profile_pic, name='change_profile_pic'),
]

BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("App_Blog.urls")),
    path("account/", include("App_Login.urls")),
    path("", views.index, name="index"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='Email', required=True, help_text='Required Field')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ProfilePicForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)
        #fields = ('__all__')

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, EditProfileForm, ProfilePicForm

# Create your views here.

def sign_up(request):
    # form = UserCreationForm()
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        form = SignUpForm(request.POST)
        if form.is_valid():
           form.save()
           registered = True
    dict = {'form':form,'registered':registered}
    return render(request,'App_Login/sign_up.html',context=dict)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
           username = form.cleaned_data.get('username')
           password = form.cleaned_data.get('password')
           user = authenticate(username=username,password=password)
           if user is not None:
               login(request,user)
               return HttpResponseRedirect(reverse('index'))
    return render(request,'App_Login/login.html', context={'form':form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    return render(request,'App_Login/profile.html',context={})


@login_required
def edit_profile(request):
    current_user = request.user
    form = EditProfileForm(instance=current_user)
    if request.method == 'POST':
        form = EditProfileForm(request.POST,instance=current_user)
        if form.is_valid():
           form.save()
           form = EditProfileForm(instance=current_user)
    return render(request,'App_Login/edit_profile.html',context={'form':form})


@login_required
def change_password(request):
    current_user = request.user
    changed = False
    # form = PasswordChangeForm(current_user)
    form = SetPasswordForm(current_user)
    if request.method == 'POST':
        # form = PasswordChangeForm(current_user,data=request.POST)
        form = SetPasswordForm(current_user,data=request.POST)
        if form.is_valid():
           form.save()
           changed = True
    return render(request,'App_Login/change_password.html',context={'form':form,'changed':changed})


@login_required
def add_profile_pic(request):
    form = ProfilePicForm()
    if request.method == 'POST':
        form = ProfilePicForm(request.POST,request.FILES)
        if form.is_valid():
           user_obj = form.save(commit=False)
           user_obj.user = request.user
           user_obj.save()
           return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request,'App_Login/add_pro_pic.html',context={'form':form})


@login_required
def change_profile_pic(request):
    form = ProfilePicForm(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePicForm(request.POST,request.FILES,instance=request.user.user_profile)
        if form.is_valid():
           form.save()
           return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request,'App_Login/add_pro_pic.html',context={'form':form})

templates/App_Login/add_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}

{% block body_block %}

<h1>Add Your Profile Picture</h1>
<form action="" method="post" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Add Profile Picture</button>
</form>

{% endblock %}

templates/App_Login/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %}
{% block body_block %}
{% if changed %}
<div class="alert alert-success">
    Password Changed Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% endif %}
<h2>Change Password:</h2>
<form action="" method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Change Password</button>
</form>
{% endblock %}

templates/App_Login/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Edit Profile {% endblock %}
{% block body_block %}
<h2>Edit Profile:</h2>
<form action="" method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Update</button>
</form>

{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
<h2>Login:</h2>
<form action="" method="post">
    {{ form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Login</button>
</form>
<br>
<p>Dont yet SignUp? <a href="{% url 'App_Login:signup' %}">Signup Here</a></p>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}

{% block title_block %} Profile {% endblock %}

{% block body_block %}

<h1>Your Profile</h1>
{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic }}" class="img img-thumbnail rounded-circle" style="width: 160px; height: 160px;">
<br>
<a href="{% url 'App_Login:change_profile_pic' %}" class="btn btn-primary btn-sm mt-3 mb-5">Change Profile Image</a>
{% else %}
<img src="/media/profile_pics/a.png" class="img img-thumbnail rounded-circle" style="width: 160px; height: 160px;">
<br>
<a href="{% url 'App_Login:add_profile_pic' %}" class="btn btn-primary btn-sm mt-3 mb-5">Add Profile Image</a>
{% endif %}
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name: {{ user.first_name }} {{ user.last_name }}</p>
<br>
<a href="{% url 'App_Login:edit_profile' %}" class="btn btn-warning btn-sm">Edit Profile</a>

{% endblock %}

templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}

{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    Account Createrd Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}

<h2>Create New Account:</h2>
<form action="" method="post">
    
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Aleady have an account?<a href="{% url 'App_Login:login' %}">Login here</a></p>

{% endif %}
{% endblock %}