App_Blog/urls.py
from django.urls import path
from . import views

app_name = "App_Blog"

urlpatterns = [
    path("", views.BlogList.as_view(), name="blog_list"),
    path("write/", views.CreateBlog.as_view(), name="create_blog"),
    path("details/<slug:slug>/", views.blog_details, name="blog_details"),
    path("liked/<pk>/", views.liked, name="liked_post"),
    path("unliked/<pk>/", views.unliked, name="unliked_post"),
    path("disliked/<pk>/", views.disliked, name="disliked_post"),
    path("undisliked/<pk>/", views.undisliked, name="undisliked_post"),
    path("myblogs/", views.MyBlog.as_view(), name="my_blogs"),
    path("edit/<pk>/", views.UpdateBlog.as_view(), name="edit_blog"),
]

App_Login/urls.py
from django.urls import path
from App_Login import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('password/', views.change_password, name='change_password'),
    path('add_profile_pic/', views.add_profile_pic, name='add_profile_pic'),
    path('change_profile_pic/', views.change_profile_pic, name='change_profile_pic'),
]

BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("App_Blog.urls")),
    path("account/", include("App_Login.urls")),
    path("", views.index, name="index"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="">M System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link img img-thumbnail rounded-circle" aria-current="page" href="{% url 'index' %}"><img src="/media/logo.png" alt="" height="20px"; width="20px";></a>
                        
                    </li>

                    {% if user.is_authenticated %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a></li>
                            <li><a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blog</a></li>
                            <li><a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a></li>
                            <br>
                            <li><a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a></li>
                        </ul>
                    </li>

                    {% else %}

                    <li class="nav-item">
                        <a class="nav-link  active" aria-current="page" href="{% url 'App_Login:login' %}">Login</a>
                    </li>

                    {% endif %}

                    

                </ul>

                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-top: 20px;">
        {% block body_block %} 
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>