App_Blog/urls.py
from django.urls import path
from . import views

app_name = "App_Blog"

urlpatterns = [
    path("", views.BlogList.as_view(), name="blog_list"),
    path("write/", views.CreateBlog.as_view(), name="create_blog"),
    path("details/<slug:slug>/", views.blog_details, name="blog_details"),
    path("liked/<pk>/", views.liked, name="liked_post"),
    path("unliked/<pk>/", views.unliked, name="unliked_post"),
    path("disliked/<pk>/", views.disliked, name="disliked_post"),
    path("undisliked/<pk>/", views.undisliked, name="undisliked_post"),
    path("myblogs/", views.MyBlog.as_view(), name="my_blogs"),
    path("edit/<pk>/", views.UpdateBlog.as_view(), name="edit_blog"),
]

BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("App_Blog.urls")),
    path("account/", include("App_Login.urls")),
    path("", views.index, name="index"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, related_name='post_author', on_delete=models.CASCADE)
    blog_title = models.CharField(max_length=264, verbose_name='Put a Title')
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name='What is on your mind?')
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return self.blog_title
    

class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name='blog_comment', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_comment', on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date',]

    def __str__(self):
        return self.comment
    
class Likes(models.Model):
    blog = models.ForeignKey(Blog, related_name='liked_blog', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='liker_user', on_delete=models.CASCADE)

    def __str__(self):
        return self.user , " likes " , self.blog

    
class Dislikes(models.Model):
    blog = models.ForeignKey(Blog, related_name='disliked_blog', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='disliker_user', on_delete=models.CASCADE)

    def __str__(self):
        return self.user , " dislikes " , self.blog
    

App_Blog/forms.py
from django import forms
from App_Blog.models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

# class BlogForm(forms.ModelForm):
#     class Meta:
#         model = Blog
#         fields = ('blog_title', 'blog_content', 'blog_image')

# class UpdateBlogForm(forms.ModelForm):
#     class Meta:
#         model = Blog
#         fields = ('blog_title', 'blog_content', 'blog_image')

# class UpdateCommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ('comment',)

# class SearchForm(forms.Form):
#     search = forms.CharField(max_length=100)

# class ContactForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     email = forms.EmailField()
#     message = forms.CharField(widget=forms.Textarea)

# class ReplyForm(forms.Form):
#     reply = forms.CharField(widget=forms.Textarea)

# class ReplyCommentForm(forms.Form):
#     reply = forms.CharField(widget=forms.Textarea)

# class ReplyReplyForm(forms.Form):
#     reply = forms.CharField(widget=forms.Textarea)

App_Blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, TemplateView, View, UpdateView
#from django.views.generic.edit import UpdateView
from App_Blog.forms import CommentForm
from App_Blog.models import Blog, Comment, Dislikes, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid

# Create your views here.

class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'App_Blog/my_blogs.html'


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    template_name = 'App_Blog/edit_blogs.html'
    fields = ('blog_title', 'blog_content', 'blog_image')
    
    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Blog:blog_details', kwargs={'slug':self.object.slug})
        # update and delete we must use reverse_lazy, this means untill i update it dont redirect
    

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'


@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False

    already_disliked = Dislikes.objects.filter(blog=blog, user=request.user)
    if already_disliked:
        disliked = True
    else:
        disliked = False
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.blog = blog
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':slug}))

    return render(request, 'App_Blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked, 'disliked':disliked})
    #return render(request, 'App_Blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked})


@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))


@login_required
def disliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_disliked = Dislikes.objects.filter(blog=blog, user=user)
    if not already_disliked:
        disliked_post = Dislikes(blog=blog, user=user)
        disliked_post.save()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))


@login_required
def undisliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_disliked = Dislikes.objects.filter(blog=blog, user=user)
    already_disliked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))




    

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ blog.blog_title }} {% endblock %}
{% block body_block %}

<div class="row">
    <div class="col-sm-6">
        <h2>{{ blog.blog_title }}</h2>
        <h4>Posted by : {{ blog.author }}</h4>
        <h6><i>Published on : {{ blog.publish_date }}</i></h6>
        <h6><i>Updated on : {{ blog.update_date }}</i></h6>
        <h6>{{ blog.liked_blog.count }} Likes | {{ blog.disliked_blog.count }} Dislikes | {{ blog.blog_comment.count }} Comments</h6>
        <!-- <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6> -->
    </div>
    <div class="col-sm-6">
        <img src="{{ blog.blog_image.url }}" class="img-fluid" alt="Responsive image" title="{{ blog.blog_title }}" width="100%">
    </div>
    <p>
        {{ blog.blog_content|linebreaks }}
    </p>
</div>

{% if not liked %}
<a href="{% url 'App_Blog:liked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-up" style="color: #11a21b;"></i></a> |
{% else %}
<a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-up fa-bounce" style="color: #11a21b;"></i></a> |
{% endif %}

{% if not disliked %}
 <a href="{% url 'App_Blog:disliked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-down" style="color: #a21111;"></i></a>
{% else %}
 <a href="{% url 'App_Blog:undisliked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-down fa-bounce" style="color: #a21111;"></i></a>
{% endif %}

<div class="row">
    <div class="col-sm-6">
        <hr>
        <h5>Comments : </h5>
        {% for comment in blog.blog_comment.all %}
        <div class="card">
            <div class="card-body">
                <h6 class="card-title"><a href="#">{{ comment.user }}</a></h6>
                <p class="card-text">{{ comment.comment }}</p>
                <h6 class="card-subtitle mb-2 text-muted">{{ comment.comment_date }}</h6>
            </div>
        </div>
        <!-- <p><a href="">{{ comment.user }}</a> {{ comment.comment }} <br><h6>{{ comment.comment_date }}</h6></p> -->
        {% endfor %}

    </div>
    <div class="col-sm-6">
        <hr>
        <h5>Leave a comment : </h5>
        <form method="post">
            {{ comment_form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Comment</button>
        </form>
    </div>
</div>
<br>
<br>

{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title_block %} Home {% endblock %}

{% block body_block %}

{% for blog in blogs %}
    <h3>{{ blog.blog_title }}</h3>
    <h6><i>{{ blog.publish_date }}</i></h6>
    <div class="row">
        <div class="col-md-4">
            <img src="{{ blog.blog_image.url }}" class="img-fluid" alt="Responsive image" title="{{ blog.blog_title }}" width="100%">
        </div>
        <div class="col-md-8">
            <p>{{ blog.blog_content|range_filter|linebreaks }} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read more</a></p>
            <h6>Posted by : <a href="#">{{ blog.author }}</a></h6>
            <!-- <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6> -->
            <h6>{{ blog.liked_blog.count }} Likes | {{ blog.disliked_blog.count }} Dislikes | {{ blog.blog_comment.count }} Comments</h6>
        </div>
    </div>
    <hr>
{% endfor %}

{% endblock %}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}  {% endblock %}
{% block body_block %}
<h2>Write Blog Here</h2>
<form method="post" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm" >Publish</button>
</form>
{% endblock %}

templates/App_Blog/edit_blogs.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{ blog.blog_title }}{% endblock %}
{% block body_block %}

{% if blog.author == user %}
<form method="post" enctype="multipart/form-data">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Update</button>
{% else %}
<p>You are not allowed to view this page</p>
</form>
{% endif %}

{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} {{ user }} {% endblock %}
{% block body_block %}

    {% for blog in user.post_author.all %}
        <h3>{{ blog.blog_title }}</h3>
        <h6><i>{{ blog.publish_date }}</i></h6>
        <div class="row">
            <div class="col-md-4">
                <img src="{{ blog.blog_image.url }}" class="img-fluid" alt="Responsive image" title="{{ blog.blog_title }}" width="100%">
            </div>
            <div class="col-md-8">
                <p>{{ blog.blog_content|range_filter|linebreaks }} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read more</a></p>
                <h6>Posted by : <a href="#">{{ blog.author }}</a></h6>
                <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
            </div>
        </div>
        <a href="{% url 'App_Blog:edit_blog' pk=blog.pk %}">Edit</a>
        <hr>
    {% endfor %}

{% endblock %}